// DeepSeek Harness Go plugin protocol (DESIGN-v2 §B.2).
//
// A plugin is an external process speaking this gRPC contract on
// localhost. The host (dsh main) launches the plugin, calls Specs() to
// enumerate tools, and forwards tool_calls from the LLM to Execute().
//
// Wire: gRPC over plaintext HTTP/2 on a TCP socket assigned by the host
// and passed to the plugin via DSH_PLUGIN_ADDR env var.
//
// Versioning: this proto lives at v1. Breaking changes require a new
// service (e.g. ToolProviderV2) per Go gRPC convention.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: internal/plugin/proto/tool_provider.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message reused by RPCs that take no arguments.
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_tool_provider_proto_rawDescGZIP(), []int{0}
}

// ToolSpec describes a single tool exposed by the plugin.
type ToolSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema object (raw bytes — we don't parse on the wire).
	Parameters []byte `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Version    string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Plugin author hint: when false, host skips Approval pre-check.
	// Host still applies any configured allowlist.
	RequiresApproval bool `protobuf:"varint,5,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
}

func (x *ToolSpec) Reset() {
	*x = ToolSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSpec) ProtoMessage() {}

func (x *ToolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSpec.ProtoReflect.Descriptor instead.
func (*ToolSpec) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_tool_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ToolSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSpec) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ToolSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ToolSpec) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

// ToolList is the response payload for Specs.
type ToolList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Specs []*ToolSpec `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
}

func (x *ToolList) Reset() {
	*x = ToolList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolList) ProtoMessage() {}

func (x *ToolList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolList.ProtoReflect.Descriptor instead.
func (*ToolList) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_tool_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ToolList) GetSpecs() []*ToolSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

// ExecuteRequest asks the plugin to invoke one tool with JSON args.
type ExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgsJson []byte `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	// call_id is opaque to the plugin; the host uses it to correlate the
	// response back to the originating tool call. The plugin may echo
	// it for logging.
	CallId string `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_tool_provider_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteRequest) GetArgsJson() []byte {
	if x != nil {
		return x.ArgsJson
	}
	return nil
}

func (x *ExecuteRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// ExecuteResponse carries the tool's outcome.
type ExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The result content (string form). For structured output, the plugin
	// is responsible for JSON-encoding it.
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsError bool   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// Optional metadata (timing, side effects). Plugin-defined.
	Meta map[string]string `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_tool_provider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_tool_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ExecuteResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_internal_plugin_proto_tool_provider_proto protoreflect.FileDescriptor

var file_internal_plugin_proto_tool_provider_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x64, 0x73, 0x68,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0xa7, 0x01, 0x0a, 0x08, 0x54, 0x6f, 0x6f, 0x6c, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x22, 0x39, 0x0a,
	0x08, 0x54, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x70, 0x65,
	0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x73, 0x68, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x05, 0x73, 0x70, 0x65, 0x63, 0x73, 0x22, 0x5a, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x61, 0x72, 0x67, 0x73, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x61, 0x72, 0x67, 0x73, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61,
	0x6c, 0x6c, 0x49, 0x64, 0x22, 0xbd, 0x01, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3c, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x73,
	0x68, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x4d,
	0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x32, 0x90, 0x01, 0x0a, 0x0c, 0x54, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x14,
	0x2e, 0x64, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x64, 0x73, 0x68, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x48, 0x0a,
	0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x64, 0x73, 0x68, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x73, 0x68, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x64, 0x65, 0x65, 0x70, 0x73,
	0x65, 0x65, 0x6b, 0x2d, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_plugin_proto_tool_provider_proto_rawDescOnce sync.Once
	file_internal_plugin_proto_tool_provider_proto_rawDescData = file_internal_plugin_proto_tool_provider_proto_rawDesc
)

func file_internal_plugin_proto_tool_provider_proto_rawDescGZIP() []byte {
	file_internal_plugin_proto_tool_provider_proto_rawDescOnce.Do(func() {
		file_internal_plugin_proto_tool_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_plugin_proto_tool_provider_proto_rawDescData)
	})
	return file_internal_plugin_proto_tool_provider_proto_rawDescData
}

var file_internal_plugin_proto_tool_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_plugin_proto_tool_provider_proto_goTypes = []any{
	(*Empty)(nil),           // 0: dsh.plugin.v1.Empty
	(*ToolSpec)(nil),        // 1: dsh.plugin.v1.ToolSpec
	(*ToolList)(nil),        // 2: dsh.plugin.v1.ToolList
	(*ExecuteRequest)(nil),  // 3: dsh.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 4: dsh.plugin.v1.ExecuteResponse
	nil,                     // 5: dsh.plugin.v1.ExecuteResponse.MetaEntry
}
var file_internal_plugin_proto_tool_provider_proto_depIdxs = []int32{
	1, // 0: dsh.plugin.v1.ToolList.specs:type_name -> dsh.plugin.v1.ToolSpec
	5, // 1: dsh.plugin.v1.ExecuteResponse.meta:type_name -> dsh.plugin.v1.ExecuteResponse.MetaEntry
	0, // 2: dsh.plugin.v1.ToolProvider.Specs:input_type -> dsh.plugin.v1.Empty
	3, // 3: dsh.plugin.v1.ToolProvider.Execute:input_type -> dsh.plugin.v1.ExecuteRequest
	2, // 4: dsh.plugin.v1.ToolProvider.Specs:output_type -> dsh.plugin.v1.ToolList
	4, // 5: dsh.plugin.v1.ToolProvider.Execute:output_type -> dsh.plugin.v1.ExecuteResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_plugin_proto_tool_provider_proto_init() }
func file_internal_plugin_proto_tool_provider_proto_init() {
	if File_internal_plugin_proto_tool_provider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_plugin_proto_tool_provider_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_plugin_proto_tool_provider_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ToolSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_plugin_proto_tool_provider_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ToolList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_plugin_proto_tool_provider_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_plugin_proto_tool_provider_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ExecuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_plugin_proto_tool_provider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugin_proto_tool_provider_proto_goTypes,
		DependencyIndexes: file_internal_plugin_proto_tool_provider_proto_depIdxs,
		MessageInfos:      file_internal_plugin_proto_tool_provider_proto_msgTypes,
	}.Build()
	File_internal_plugin_proto_tool_provider_proto = out.File
	file_internal_plugin_proto_tool_provider_proto_rawDesc = nil
	file_internal_plugin_proto_tool_provider_proto_goTypes = nil
	file_internal_plugin_proto_tool_provider_proto_depIdxs = nil
}
