// DeepSeek Harness Go plugin protocol (DESIGN-v2 §B.2).
//
// A plugin is an external process speaking this gRPC contract on
// localhost. The host (dsh main) launches the plugin, calls Specs() to
// enumerate tools, and forwards tool_calls from the LLM to Execute().
//
// Wire: gRPC over plaintext HTTP/2 on a TCP socket assigned by the host
// and passed to the plugin via DSH_PLUGIN_ADDR env var.
//
// Versioning: this proto lives at v1. Breaking changes require a new
// service (e.g. ToolProviderV2) per Go gRPC convention.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.1
// source: internal/plugin/proto/tool_provider.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ToolProvider_Specs_FullMethodName   = "/dsh.plugin.v1.ToolProvider/Specs"
	ToolProvider_Execute_FullMethodName = "/dsh.plugin.v1.ToolProvider/Execute"
)

// ToolProviderClient is the client API for ToolProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToolProvider is the contract every plugin must implement.
type ToolProviderClient interface {
	Specs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToolList, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type toolProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewToolProviderClient(cc grpc.ClientConnInterface) ToolProviderClient {
	return &toolProviderClient{cc}
}

func (c *toolProviderClient) Specs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToolList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolList)
	err := c.cc.Invoke(ctx, ToolProvider_Specs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolProviderClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, ToolProvider_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolProviderServer is the server API for ToolProvider service.
// All implementations must embed UnimplementedToolProviderServer
// for forward compatibility
//
// ToolProvider is the contract every plugin must implement.
type ToolProviderServer interface {
	Specs(context.Context, *Empty) (*ToolList, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedToolProviderServer()
}

// UnimplementedToolProviderServer must be embedded to have forward compatible implementations.
type UnimplementedToolProviderServer struct {
}

func (UnimplementedToolProviderServer) Specs(context.Context, *Empty) (*ToolList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Specs not implemented")
}
func (UnimplementedToolProviderServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedToolProviderServer) mustEmbedUnimplementedToolProviderServer() {}

// UnsafeToolProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolProviderServer will
// result in compilation errors.
type UnsafeToolProviderServer interface {
	mustEmbedUnimplementedToolProviderServer()
}

func RegisterToolProviderServer(s grpc.ServiceRegistrar, srv ToolProviderServer) {
	s.RegisterService(&ToolProvider_ServiceDesc, srv)
}

func _ToolProvider_Specs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolProviderServer).Specs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolProvider_Specs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolProviderServer).Specs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolProvider_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolProviderServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolProvider_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolProviderServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolProvider_ServiceDesc is the grpc.ServiceDesc for ToolProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dsh.plugin.v1.ToolProvider",
	HandlerType: (*ToolProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Specs",
			Handler:    _ToolProvider_Specs_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _ToolProvider_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugin/proto/tool_provider.proto",
}
